sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-hydrator
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-hydrator.git
    - secure: "xMnwSntQA+rIsQIIklwziEROWMlF9vsq7L1BOJwnNMFmfImnn/2RxHdqqtQ6q7npsHioUqn23YZyFTLCGZiM7SLcBQndiW1Qmgz8VE2hk1ur+d2PIewu7v3aTgOOB+igK0Re43ZQKX/Vl2C92IlBmilyWzFBqE81kdw0NmxHq8QqpNAgnTkYaye4MOiW+giLtdkCSHHYn6/zmOgc0A630X7YKy7Ru+bYGGXXVb2jzq7mdapE0XZpgjFkYiwwOgA8AQLwWJF87QwaGrdeej1PbAInQDoeMWf9o2C5Ezl57+IWJfR6yTs29zFDUXo6hcWyQ4Rurpgei0Jt30LDZohZ4xY0LZkJ0wochprh5riXmQ2cM/i/RvQjQ2hgJOcDHyUPYfaoyD4CRgA1KvkjD7dRypQ03cPyjHXluZat+ZQkFMa6W5K/M2brGLRhW3echko3/1riMEzFshhqMO7RtZ9GeHg8fNxlgJFZI6R8KvIE+pM7OiZUdPYlfqOSZKr2kxhF2mJQ+a7I3EguLc2cgvu4c8IL34dOrmInhsj5kkIapLpiEIyN0G8rV6oI/nHXYBDgrEckjozjAkdOkInf/TowRNODQmrR7eUeBJCLPbRHFcY5aE4cGGGl7J1KM6rx2vV9Boc3KTxY0+cC9JegR8X7UaqGLqTSJ7k5FyapoxfYSJA="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.5
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
        - EVENT_MANAGER_VERSION="^2.6.2"
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
        - EVENT_MANAGER_VERSION="^2.6.2"
    - php: 7
    - php: 7
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
        - EVENT_MANAGER_VERSION="^2.6.2"
    - php: hhvm
    - php: hhvm
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
        - EVENT_MANAGER_VERSION="^2.6.2"
  allow_failures:
    - php: 7

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $EVENT_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:$EVENT_MANAGER_VERSION" ; fi
  - if [[ $EVENT_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:^3.0" ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
