sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
        - EXECUTE_TEST_COVERALLS=true
    - php: 7
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
    - php: hhvm
      env:
        - SERVICE_MANAGER_VERSION="^2.7.3"
  allow_failures:
    - php: 7

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0" ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
