docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - "Quick Start": quick-start.md
    - Reference:
      - "Filters": filter.md
      - "Strategies": strategy.md
      - "Aggregates": aggregate.md
      - "Naming Strategies":
        - "Identity": naming-strategy/identity-naming-strategy.md
        - "Mapping": naming-strategy/map-naming-strategy.md
        - "Underscore Mapping": naming-strategy/underscore-naming-strategy.md
        - "Composite": naming-strategy/composite-naming-strategy.md
site_name: zend-hydrator
site_description: "Serialize objects to arrays, and vice versa"
repo_url: 'https://github.com/zendframework/zend-hydrator'
