docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - "Quick Start": v3/quick-start.md
    - Reference:
      - "Filters": v3/filter.md
      - "Strategies": v3/strategy.md
      - "Aggregates": v3/aggregate.md
      - "Naming Strategies":
        - "Identity": v3/naming-strategy/identity-naming-strategy.md
        - "Mapping": v3/naming-strategy/map-naming-strategy.md
        - "Underscore Mapping": v3/naming-strategy/underscore-naming-strategy.md
        - "Composite": v3/naming-strategy/composite-naming-strategy.md
      - Migration: v3/migration.md
    - v2:
        - "Quick Start": v2/quick-start.md
        - Reference:
          - "Filters": v2/filter.md
          - "Strategies": v2/strategy.md
          - "Aggregates": v2/aggregate.md
          - "Naming Strategies":
            - "Identity": v2/naming-strategy/identity-naming-strategy.md
            - "Mapping": v2/naming-strategy/map-naming-strategy.md
            - "Underscore Mapping": v2/naming-strategy/underscore-naming-strategy.md
            - "Composite": v2/naming-strategy/composite-naming-strategy.md
    - "_hidden-legacy-page-links":
        - "_quick_start": quick-start.md
        - "_filters": filter.md
        - "_strategies": strategy.md
        - "_aggregates": aggregate.md
        - "_naming_strategies-identity": naming-strategy/identity-naming-strategy.md
        - "_naming_strategies-mapping": naming-strategy/map-naming-strategy.md
        - "_naming_strategies-underscore_mapping": naming-strategy/underscore-naming-strategy.md
        - "_naming_strategies-composite": naming-strategy/composite-naming-strategy.md
site_name: zend-hydrator
site_description: "Serialize objects to arrays, and vice versa"
repo_url: 'https://github.com/zendframework/zend-hydrator'
